import { useState } from 'react'

function ScoreBar({ label, value }) {
  return (
    <div className="flex items-center gap-2 text-xs">
      <span className="w-24" style={{ color: 'var(--doaide-text-secondary)' }}>{label}</span>
      <div className="flex-1 h-1.5 rounded-full" style={{ background: 'var(--doaide-border)' }}>
        <div
          className="h-full rounded-full transition-all"
          style={{
            width: `${value * 10}%`,
            background: value >= 7 ? 'var(--doaide-success)' : value >= 4 ? 'var(--doaide-gold)' : 'var(--doaide-error)',
          }}
        />
      </div>
      <span className="w-6 text-right font-mono text-xs" style={{ color: 'var(--doaide-text-muted)' }}>
        {value.toFixed(1)}
      </span>
    </div>
  )
}

function DomainBadge({ domain, available }) {
  const bg = available === true ? 'var(--doaide-success)' : available === false ? 'var(--doaide-error)' : 'var(--doaide-text-muted)'
  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-mono"
      style={{ background: `${bg}20`, color: bg }}
    >
      {available === true ? '✓' : available === false ? '✗' : '?'} {domain}
    </span>
  )
}

export default function NameCard({ name, onSave }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(name.name)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const shareWhatsApp = () => {
    const text = `Check out this business name I found: ${name.name} - "${name.tagline}" 🚀\n\nGenerated by BizNameAI: https://bizname.doaide.com`
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank')
  }

  const shareTwitter = () => {
    const text = `I found the perfect business name: ${name.name} ✨\n\nGenerate yours free at https://bizname.doaide.com`
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`, '_blank')
  }

  return (
    <div
      className="rounded-xl p-5 transition-all hover:shadow-lg"
      style={{
        background: 'var(--doaide-surface)',
        border: '1px solid var(--doaide-border)',
      }}
    >
      <div className="flex items-start justify-between mb-2">
        <div>
          <h3 className="text-xl font-bold m-0" style={{ color: 'var(--doaide-text)' }}>{name.name}</h3>
          <p className="text-sm mt-1 mb-0" style={{ color: 'var(--doaide-text-secondary)' }}>{name.tagline}</p>
        </div>
        <div
          className="flex items-center justify-center w-10 h-10 rounded-lg text-sm font-bold"
          style={{
            background: 'var(--doaide-gold-bg)',
            color: 'var(--doaide-gold)',
          }}
        >
          {name.scores.overall.toFixed(1)}
        </div>
      </div>

      <div className="flex flex-wrap gap-1.5 mt-3 mb-3">
        {name.domains.map((d) => (
          <DomainBadge key={d.domain} domain={d.domain} available={d.available} />
        ))}
      </div>

      <div className="space-y-1.5 mb-4">
        <ScoreBar label="Memorability" value={name.scores.memorability} />
        <ScoreBar label="Brandability" value={name.scores.brandability} />
        <ScoreBar label="Length" value={name.scores.length} />
      </div>

      <div className="flex items-center gap-2 flex-wrap">
        <button
          onClick={handleCopy}
          className="px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer transition-colors"
          style={{
            background: copied ? 'var(--doaide-success)' : 'var(--doaide-gold)',
            color: 'var(--doaide-text-on-gold)',
            border: 'none',
          }}
        >
          {copied ? '✓ Copied' : 'Copy'}
        </button>
        <button
          onClick={shareWhatsApp}
          className="px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer"
          style={{
            background: '#25D366',
            color: '#fff',
            border: 'none',
          }}
        >
          WhatsApp
        </button>
        <button
          onClick={shareTwitter}
          className="px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer"
          style={{
            background: '#1DA1F2',
            color: '#fff',
            border: 'none',
          }}
        >
          Twitter
        </button>
        {onSave && (
          <button
            onClick={() => onSave(name.id)}
            className="px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer"
            style={{
              background: 'transparent',
              color: 'var(--doaide-gold)',
              border: '1px solid var(--doaide-gold)',
            }}
          >
            ♥ Save
          </button>
        )}
      </div>

      <div className="mt-3 flex flex-wrap gap-1.5">
        {name.socials.map((s) => (
          <span
            key={s.platform}
            className="text-xs px-2 py-0.5 rounded"
            style={{
              background: s.likely_available ? 'rgba(52,211,153,0.1)' : 'rgba(248,113,113,0.1)',
              color: s.likely_available ? 'var(--doaide-success)' : 'var(--doaide-error)',
            }}
          >
            {s.platform}: {s.handle}
          </span>
        ))}
      </div>
    </div>
  )
}
