export const NICE_CLASSES = [
  {
    number: 1,
    title: 'Chemicals',
    description: 'Industrial chemicals, scientific chemicals, photographic chemicals, agricultural chemicals, fire extinguishing compositions, tempering substances, soldering chemicals.',
    examples: ['Industrial adhesives', 'Fertilizers', 'Photographic film chemicals', 'Artificial resins (unprocessed)', 'Manure for agriculture'],
    relatedClasses: [2, 5, 17],
  },
  {
    number: 2,
    title: 'Paints',
    description: 'Paints, varnishes, lacquers, anti-rust preparations, colorants, dyes, inks for printing and marking, raw natural resins, metals in foil and powder form for painting.',
    examples: ['Wall paints', 'Wood stains', 'Printing ink', 'Anti-corrosion coatings', 'Food dyes'],
    relatedClasses: [1, 3, 16],
  },
  {
    number: 3,
    title: 'Cosmetics & Cleaning',
    description: 'Cleaning preparations, polishing preparations, soaps, perfumery, essential oils, cosmetics, hair lotions, dentifrices.',
    examples: ['Shampoo', 'Lipstick', 'Toothpaste', 'Laundry detergent', 'Perfume'],
    relatedClasses: [5, 21, 44],
  },
  {
    number: 4,
    title: 'Lubricants & Fuels',
    description: 'Industrial oils and greases, lubricants, fuel, illuminants, candles, wicks for lighting.',
    examples: ['Motor oil', 'Diesel fuel', 'Scented candles', 'Lamp wicks', 'Industrial grease'],
    relatedClasses: [1, 7, 11],
  },
  {
    number: 5,
    title: 'Pharmaceuticals',
    description: 'Pharmaceutical preparations, medical and veterinary preparations, sanitary preparations, dietetic food and substances for medical use, plasters, dressings, disinfectants.',
    examples: ['Ayurvedic medicines', 'Vitamins', 'Surgical dressings', 'Baby food (medicated)', 'Mosquito repellent'],
    relatedClasses: [3, 10, 44],
  },
  {
    number: 6,
    title: 'Metal Goods',
    description: 'Common metals and their alloys, metal building materials, transportable buildings of metal, non-electric cables and wires of metal, hardware, pipes and tubes of metal.',
    examples: ['Steel pipes', 'Metal doors', 'Nails and screws', 'Wire mesh', 'Metal safes'],
    relatedClasses: [7, 19, 20],
  },
  {
    number: 7,
    title: 'Machinery',
    description: 'Machines and machine tools, motors and engines, machine coupling and transmission components, agricultural implements, incubators for eggs, automatic vending machines.',
    examples: ['Sewing machines', 'Printing presses', 'Electric generators', 'Food processing machines', 'Pumps'],
    relatedClasses: [6, 9, 11],
  },
  {
    number: 8,
    title: 'Hand Tools',
    description: 'Hand tools and implements (hand-operated), cutlery, side arms, razors.',
    examples: ['Kitchen knives', 'Spanners', 'Razors', 'Scissors', 'Garden shears'],
    relatedClasses: [7, 21],
  },
  {
    number: 9,
    title: 'Electronics & Software',
    description: 'Scientific, nautical, surveying, photographic, cinematographic, optical, measuring, signaling, life-saving apparatus, computer hardware and software, mobile apps, downloadable content.',
    examples: ['Mobile phones', 'Computer software', 'Mobile apps', 'USB drives', 'Fire extinguishers', 'Smartwatches'],
    relatedClasses: [35, 38, 42],
  },
  {
    number: 10,
    title: 'Medical Apparatus',
    description: 'Surgical, medical, dental and veterinary apparatus and instruments, artificial limbs, eyes and teeth, orthopedic articles, suture materials.',
    examples: ['Stethoscopes', 'Surgical gloves', 'Hearing aids', 'Prosthetic limbs', 'Blood pressure monitors'],
    relatedClasses: [5, 44],
  },
  {
    number: 11,
    title: 'Environmental Control',
    description: 'Apparatus for lighting, heating, steam generating, cooking, refrigerating, drying, ventilating, water supply and sanitary purposes.',
    examples: ['LED lights', 'Air conditioners', 'Water purifiers', 'Microwave ovens', 'Solar panels'],
    relatedClasses: [7, 9, 21],
  },
  {
    number: 12,
    title: 'Vehicles',
    description: 'Vehicles, apparatus for locomotion by land, air or water.',
    examples: ['Cars', 'Bicycles', 'Motorcycles', 'Tyres', 'Electric scooters'],
    relatedClasses: [7, 37, 39],
  },
  {
    number: 13,
    title: 'Firearms',
    description: 'Firearms, ammunition and projectiles, explosives, fireworks.',
    examples: ['Pistols', 'Ammunition cartridges', 'Fireworks', 'Explosive devices', 'Signal flares'],
    relatedClasses: [8, 25],
  },
  {
    number: 14,
    title: 'Jewellery',
    description: 'Precious metals and their alloys, jewellery, precious stones, horological and chronometric instruments.',
    examples: ['Gold jewellery', 'Watches', 'Diamonds', 'Clocks', 'Cufflinks'],
    relatedClasses: [18, 25, 26],
  },
  {
    number: 15,
    title: 'Musical Instruments',
    description: 'Musical instruments.',
    examples: ['Guitars', 'Pianos', 'Drums', 'Tabla', 'Sitars'],
    relatedClasses: [9, 41],
  },
  {
    number: 16,
    title: 'Paper & Printed Matter',
    description: 'Paper, cardboard, printed matter, bookbinding material, photographs, stationery, adhesives for stationery, typewriters and office requisites, instructional and teaching material.',
    examples: ['Books', 'Notebooks', 'Greeting cards', 'Calendars', 'Stickers'],
    relatedClasses: [2, 35, 41],
  },
  {
    number: 17,
    title: 'Rubber Products',
    description: 'Rubber, gutta-percha, gum, asbestos, mica; plastics in extruded form, packing, stopping and insulating materials, flexible pipes not of metal.',
    examples: ['Rubber sheets', 'Plastic film', 'Insulation tape', 'Rubber gaskets', 'Foam padding'],
    relatedClasses: [1, 6, 19],
  },
  {
    number: 18,
    title: 'Leather Goods',
    description: 'Leather and imitations of leather; animal skins, hides; trunks and travelling bags; umbrellas, parasols and walking sticks; whips, harness and saddlery.',
    examples: ['Handbags', 'Wallets', 'Suitcases', 'Leather belts', 'Umbrellas'],
    relatedClasses: [14, 25, 26],
  },
  {
    number: 19,
    title: 'Building Materials',
    description: 'Building materials (non-metallic); non-metallic rigid pipes for building; asphalt, pitch, tar; transportable buildings not of metal; monuments not of metal.',
    examples: ['Bricks', 'Cement', 'Timber', 'Ceramic tiles', 'Glass (building)'],
    relatedClasses: [6, 17, 37],
  },
  {
    number: 20,
    title: 'Furniture',
    description: 'Furniture, mirrors, picture frames; goods of wood, cork, reed, cane, wicker, horn, bone, ivory, whalebone, shell, amber, mother-of-pearl, meerschaum; plastics goods.',
    examples: ['Sofas', 'Office chairs', 'Mattresses', 'Shelves', 'Wooden handicrafts'],
    relatedClasses: [6, 21, 24],
  },
  {
    number: 21,
    title: 'Household Utensils',
    description: 'Household or kitchen utensils and containers; combs and sponges; brushes, glassware, porcelain and earthenware.',
    examples: ['Cooking pots', 'Water bottles', 'Toothbrushes', 'Ceramic mugs', 'Brooms'],
    relatedClasses: [3, 8, 11, 20],
  },
  {
    number: 22,
    title: 'Ropes & Fibres',
    description: 'Ropes, string, nets, tents, awnings, tarpaulins, sails, sacks and bags; padding and stuffing materials; raw fibrous textile materials.',
    examples: ['Jute bags', 'Fishing nets', 'Camping tents', 'Cotton wadding', 'Nylon ropes'],
    relatedClasses: [23, 24, 25],
  },
  {
    number: 23,
    title: 'Yarns & Threads',
    description: 'Yarns and threads for textile use.',
    examples: ['Cotton yarn', 'Silk thread', 'Wool yarn', 'Synthetic thread', 'Embroidery thread'],
    relatedClasses: [22, 24, 25, 26],
  },
  {
    number: 24,
    title: 'Textiles',
    description: 'Textiles and textile goods, not included in other classes; bed and table covers.',
    examples: ['Bed sheets', 'Curtains', 'Towels', 'Tablecloths', 'Blankets'],
    relatedClasses: [20, 22, 23, 25],
  },
  {
    number: 25,
    title: 'Clothing',
    description: 'Clothing, footwear, headgear.',
    examples: ['T-shirts', 'Sarees', 'Running shoes', 'Caps', 'Jackets'],
    relatedClasses: [14, 18, 24, 35],
  },
  {
    number: 26,
    title: 'Lace & Embroidery',
    description: 'Lace and embroidery, ribbons and braid; buttons, hooks and eyes, pins and needles; artificial flowers.',
    examples: ['Zippers', 'Sewing buttons', 'Hair clips', 'Artificial flowers', 'Embroidery patches'],
    relatedClasses: [14, 23, 25],
  },
  {
    number: 27,
    title: 'Floor Coverings',
    description: 'Carpets, rugs, mats, linoleum and other materials for covering existing floors; wall hangings (non-textile).',
    examples: ['Carpets', 'Yoga mats', 'Doormats', 'Floor tiles (non-building)', 'Artificial turf'],
    relatedClasses: [19, 20, 24],
  },
  {
    number: 28,
    title: 'Games & Toys',
    description: 'Games and playthings; gymnastic and sporting articles; decorations for Christmas trees.',
    examples: ['Board games', 'Cricket bats', 'Video game controllers', 'Dolls', 'Fitness equipment'],
    relatedClasses: [9, 25, 41],
  },
  {
    number: 29,
    title: 'Meat & Processed Foods',
    description: 'Meat, fish, poultry and game; meat extracts; preserved, frozen, dried and cooked fruits and vegetables; jellies, jams; eggs, milk and dairy products; edible oils and fats.',
    examples: ['Pickles', 'Paneer', 'Frozen vegetables', 'Cheese', 'Cooking oil'],
    relatedClasses: [30, 31, 43],
  },
  {
    number: 30,
    title: 'Staple Foods',
    description: 'Coffee, tea, cocoa, sugar, rice, flour, bread, pastries, confectionery, honey, spices, sauces, ice cream.',
    examples: ['Chai (tea)', 'Basmati rice', 'Masala spices', 'Biscuits', 'Chocolate'],
    relatedClasses: [29, 31, 32, 43],
  },
  {
    number: 31,
    title: 'Agricultural Products',
    description: 'Raw and unprocessed agricultural, aquacultural, horticultural and forestry products; raw and unprocessed grains and seeds; fresh fruits and vegetables; live animals; malt.',
    examples: ['Fresh fruits', 'Seeds', 'Pet food', 'Raw wheat', 'Live fish'],
    relatedClasses: [1, 29, 30, 44],
  },
  {
    number: 32,
    title: 'Beverages (Non-Alcoholic)',
    description: 'Beers; mineral and aerated waters and other non-alcoholic drinks; fruit drinks and fruit juices; syrups and other preparations for making beverages.',
    examples: ['Mineral water', 'Fruit juice', 'Energy drinks', 'Lassi', 'Soft drinks'],
    relatedClasses: [30, 33, 43],
  },
  {
    number: 33,
    title: 'Alcoholic Beverages',
    description: 'Alcoholic beverages (except beers).',
    examples: ['Wine', 'Whisky', 'Rum', 'Vodka', 'Gin'],
    relatedClasses: [32, 43],
  },
  {
    number: 34,
    title: 'Tobacco',
    description: 'Tobacco; smokers\' articles; matches.',
    examples: ['Cigarettes', 'Cigars', 'E-cigarettes', 'Lighters', 'Hookah tobacco'],
    relatedClasses: [4],
  },
  {
    number: 35,
    title: 'Advertising & Business',
    description: 'Advertising, business management, business administration, office functions, retail and wholesale services, online marketplace services.',
    examples: ['Digital marketing agencies', 'E-commerce platforms', 'Franchise services', 'Market research', 'Import-export services'],
    relatedClasses: [9, 38, 41, 42],
  },
  {
    number: 36,
    title: 'Insurance & Finance',
    description: 'Insurance; financial affairs; monetary affairs; real estate affairs.',
    examples: ['Banking services', 'Insurance policies', 'Mutual funds', 'Real estate brokerage', 'UPI payment services'],
    relatedClasses: [35, 37],
  },
  {
    number: 37,
    title: 'Construction & Repair',
    description: 'Building construction; repair; installation services.',
    examples: ['House construction', 'Car repair', 'Mobile phone repair', 'Plumbing', 'Electrical installation'],
    relatedClasses: [6, 19, 36, 42],
  },
  {
    number: 38,
    title: 'Telecommunications',
    description: 'Telecommunications.',
    examples: ['Internet service providers', 'Mobile networks', 'Broadcasting', 'Video conferencing', 'Chat platforms'],
    relatedClasses: [9, 35, 41, 42],
  },
  {
    number: 39,
    title: 'Transport & Storage',
    description: 'Transport; packaging and storage of goods; travel arrangement.',
    examples: ['Courier services', 'Ride-hailing', 'Warehouse storage', 'Travel booking', 'Moving services'],
    relatedClasses: [12, 35, 43],
  },
  {
    number: 40,
    title: 'Material Treatment',
    description: 'Treatment of materials.',
    examples: ['Printing services', 'Textile dyeing', 'Metal plating', 'Food processing', 'Water treatment'],
    relatedClasses: [7, 37, 42],
  },
  {
    number: 41,
    title: 'Education & Entertainment',
    description: 'Education; providing of training; entertainment; sporting and cultural activities.',
    examples: ['Online courses (EdTech)', 'Coaching institutes', 'Film production', 'Event management', 'Fitness training'],
    relatedClasses: [9, 16, 35, 38, 42],
  },
  {
    number: 42,
    title: 'IT & Scientific Services',
    description: 'Scientific and technological services, research and design, industrial analysis, computer hardware and software design, SaaS, cloud computing, web development.',
    examples: ['SaaS platforms', 'Web development', 'Cloud hosting', 'App development', 'UI/UX design'],
    relatedClasses: [9, 35, 38, 41, 45],
  },
  {
    number: 43,
    title: 'Food & Accommodation',
    description: 'Services for providing food and drink; temporary accommodation.',
    examples: ['Restaurants', 'Hotels', 'Cloud kitchens', 'Catering', 'Cafes'],
    relatedClasses: [29, 30, 32, 39],
  },
  {
    number: 44,
    title: 'Medical & Beauty Services',
    description: 'Medical services; veterinary services; hygienic and beauty care; agriculture, horticulture and forestry services.',
    examples: ['Hospitals', 'Beauty salons', 'Dental clinics', 'Veterinary clinics', 'Ayurvedic treatments'],
    relatedClasses: [3, 5, 10, 31],
  },
  {
    number: 45,
    title: 'Legal & Security Services',
    description: 'Legal services; security services for physical protection; personal and social services rendered by others to meet the needs of individuals.',
    examples: ['Law firms', 'Private investigation', 'Security guard services', 'IP attorneys', 'Wedding planning'],
    relatedClasses: [35, 36, 42],
  },
]

export const POPULAR_CATEGORIES = [
  { label: 'Technology', icon: '💻', classNumbers: [9, 35, 38, 42] },
  { label: 'Food & Beverage', icon: '🍽️', classNumbers: [29, 30, 31, 32, 33, 43] },
  { label: 'Fashion', icon: '👗', classNumbers: [14, 18, 24, 25, 26] },
  { label: 'Healthcare', icon: '🏥', classNumbers: [5, 10, 44] },
  { label: 'Education', icon: '📚', classNumbers: [16, 41] },
  { label: 'Real Estate', icon: '🏠', classNumbers: [19, 36, 37] },
  { label: 'Finance', icon: '💰', classNumbers: [35, 36] },
]
